# Generated by Django 5.2.7 on 2025-10-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='trainer',
            name='specialization',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
