# Generated by Django 5.2.7 on 2025-10-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_trainer_contact_trainer_specialization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainer',
            options={'ordering': ['position', 'first_name', 'last_name']},
        ),
        migrations.AddField(
            model_name='trainer',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
