# Generated by Django 5.2.7 on 2025-10-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_alter_trainer_options_trainer_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='trainer',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_id__isnull', False), models.Q(('employee_id', ''), _negated=True)), fields=('employee_id',), name='unique_trainer_employee_id_when_set'),
        ),
    ]
