# Generated by Django 5.2.7 on 2025-10-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['position', 'name']},
        ),
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
