# Generated by Django 5.2.7 on 2025-10-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_options_staff_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='staff',
            constraint=models.UniqueConstraint(condition=models.Q(('staff_id__isnull', False), models.Q(('staff_id', ''), _negated=True)), fields=('staff_id',), name='unique_staff_id_when_set'),
        ),
    ]
