# Generated by Django 5.2.7 on 2025-10-22 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_remove_payment_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
