# Generated by Django 5.2.7 on 2025-10-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_alter_payment_paid_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='membership_type',
            field=models.CharField(choices=[('3', '3 months'), ('6', '6 months'), ('9', '9 months'), ('12', '1 year')], default='3', max_length=2),
        ),
    ]
