# Generated by Django 5.2.7 on 2025-10-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_member_date_of_joining_member_membership_due_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['position', 'name']},
        ),
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
