# Generated by Django 5.2.7 on 2025-10-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_member_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(condition=models.Q(('member_id__isnull', False), models.Q(('member_id', ''), _negated=True)), fields=('member_id',), name='unique_member_id_when_set'),
        ),
    ]
